### PR TITLE
Upgrade vanilla 2.0.0

### LINKED ISSUE #216: The "who's using vanilla" logos on the homepage should be links
I'd have thought the logos under "who's using vanilla" should probably be links to the sites where vanilla is used. This would make sense to me.

image

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Fixes for 2.0.0:
- Upped vanilla-framework to v2.0.0-beta.1
- Fixed footer
- Logo list
- Homepage layout
- Update URLs

## QA

 Browse the site and compare to live

## Issue / Card

Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2278

also

Fixes #216 #217

### CODE REVIEW

**Comment by nottrobin** [comment]
You may want to consider these out-of-scope for this PR, but I noticed a couple of things:

- Shouldn't `blazy` be in `devDependencies`?
- What happened to my `devDependenciesComments` section, where I explained that `vanilla-framework` is only in dependencies for displaying docs?

**Comment by deadlight** [comment]
@nottrobin are you thinking of the vanilla-framework project? This one doesn't host the docs.

**Comment by nottrobin** [comment]
@deadlight I am! But still, the blazy thing.

**Comment by deadlight** [comment]
@nottrobin sure, I'll update that

**Comment by kwm14** [comment]
When upgrading to `beta.1` or official `2.0.0` release please make sure to tackle this [issue](https://github.com/canonical-web-and-design/vanillaframework.io/issues/215) 😄

**Comment by nottrobin** [comment]
I suppose it might make sense as part of this PR to update the links in the footer to point to the correct repository. For your consideration.

**Comment by nottrobin** [comment]
Oh also links to practices repo here: https://vanillaframework-io-canonical-web-and-design-pr-212.run.demo.haus/coding-standards

**Comment by deadlight** [comment]
@nottrobin good spot, will do

**Comment by deadlight** [comment]
@nottrobin updated

**Comment by nottrobin** [comment]
@deadlight practices links in https://vanillaframework-io-canonical-web-and-design-pr-212.run.demo.haus/coding-standards are still wrong - ideally this would now point at https://canonical-web-and-design.github.io/practices/

**Comment by deadlight** [comment]
@nottrobin oh, I see. I can change it to the hosted site, sure.

**Comment by deadlight** [comment]
@nottrobin ... and done

**Comment by nottrobin** [comment]
Thanks! Checking now.

**Comment by nottrobin** [comment]
This is now getting further and further away from the intended scope of this PR, but I filed #216 which you can address here if you like =D

**Comment by nottrobin** [comment]
Also https://github.com/canonical-web-and-design/vanillaframework.io/issues/217

**Comment by nottrobin** [comment]
Similarly, shouldn't "Download v2.0.0" link to https://github.com/canonical-web-and-design/vanilla-framework/releases/tag/v2.0.0 (which doesn't exist yet) ?

**Comment by deadlight** [comment]
@nottrobin I may as well make those changes, too.

**Comment by deadlight** [comment]
@nottrobin @kwm14 I've done as many changes as I want to do before release. Can you take another look, please?

**Comment by anthonydillon** [comment]
There are a few small screen issues.
- the menu when opened doesn't not span the full width
- the spacing looks much more tighter and not as good as live
- the social icons are much smaller

**Comment by deadlight** [comment]
@kwm notes:
- main CTA in hero - make primary
- Get involved / subscribe box - fix layout

**Comment by deadlight** [comment]
@kwm design-approved at my desk

**Pull request merged**
